runtime: go122

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  # 指定した min_pending_latency 未満の場合、App Engine は新しいインスタンスを作成しません
  min_pending_latency: 3000ms
  # 新しいインスタンスを起動するための CPU 使用率のしきい値
  target_cpu_utilization: 0.8

# 静的ファイル
handlers:
# 常に https
- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: (.*)/robots.txt
  static_files: web/robots.txt
  upload: web/robots.txt

- url: (.*)/favicon.ico
  static_files: web/favicon.ico
  upload: web/favicon.ico

- url: (.*)/humans.txt
  static_files: web/humans.txt
  upload: web/humans.txt
