# まずは go.mod とか Svelte をインストールするための初期を作る
services:
  local_test:
    build:
      # この ファイルからの相対パスで書けばいいと思った
      # context: .
      # しかし Dockerfile では 親ディレクトリが見えないため 最初から親ディレクトリとする
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    image: local:test
    container_name: local_test
    tty: true
    command: bash
    volumes:
      - ../:/app:rw
      # もし ホストに node_module があっても マウントしないようにする
      # コンテナ側の node_modules を ホストと同期しない
      - test-node_modules:/app/frontend/local_test_svelte/node_modules
    ports:
      - "127.0.0.1:5001:8080"
      - "127.0.0.1:5002:8081"
volumes:
  test-node_modules:
    name: all_in_test-node_modules
    driver: local
