name: Build and Deploy to App Engine

on:
  # push:
  #   branches: 
  #     - "main"
  workflow_dispatch:

# GCP_PROJECT_ID: Google Cloud プロジェクト ID


jobs:
  deploy:
    name: デプロイの job
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: コードの Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Google Auth を行う
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: App Engine に Deploy する
        id: deploy-to-app-engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          working_directory: ./backend
          deliverables: ./app.yaml

      # 必要に応じて、後続のステップで Cloud Run の URL 出力を使用
      - name: App Engine の URL 出力
        id: show-output
        run: echo ${{ steps.deploy-to-app-engine.outputs.version_url }}
